defmodule Cantor.Repo.Migrations.MusicDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:patterns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :pattern_type, :text, null: false
      add :cadence_code, :text, null: false
      add :amf_signature, :map, default: %{}
      add :parameters, :map, default: %{}
      add :tags, {:array, :text}, default: []
      add :is_public, :boolean, default: false
      add :difficulty_level, :bigint, default: 5
      add :bpm_range, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "patterns_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :composition_id, :uuid
    end

    create table(:compositions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:patterns) do
      modify :composition_id,
             references(:compositions,
               column: :id,
               name: "patterns_composition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:patterns, [:user_id, :name], name: "patterns_unique_name_per_user_index")

    alter table(:compositions) do
      add :title, :text, null: false
      add :scoredown_content, :text
      add :jsonld_graph, :map, default: %{}
      add :amf_data, :map, default: %{}
      add :consciousness_params, :map
      add :is_public, :boolean, default: false
      add :tags, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "compositions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:compositions, [:user_id, :title],
             name: "compositions_unique_title_per_user_index"
           )

    create table(:composition_patterns, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :usage_context, :text
      add :parameters, :map, default: %{}
      add :position_in_composition, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :composition_id,
          references(:compositions,
            column: :id,
            name: "composition_patterns_composition_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :pattern_id,
          references(:patterns,
            column: :id,
            name: "composition_patterns_pattern_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:composition_patterns, [:composition_id, :pattern_id],
             name: "composition_patterns_unique_composition_pattern_index"
           )

    create table(:collaborations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :status, :text, default: "active"
      add :collaboration_type, :text, default: "human_only"
      add :shared_consciousness, :map
      add :operational_transform_log, {:array, :map}, default: []
      add :participant_cursors, :map, default: %{}
      add :session_metadata, :map, default: %{}
      add :ai_participants, {:array, :text}, default: []
      add :max_participants, :bigint, default: 10
      add :is_public, :boolean, default: false
      add :last_activity_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :composition_id,
          references(:compositions,
            column: :id,
            name: "collaborations_composition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :owner_id,
          references(:users,
            column: :id,
            name: "collaborations_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:collaboration_participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "participant"
      add :joined_at, :utc_datetime
      add :last_active_at, :utc_datetime
      add :consciousness_sync_status, :text, default: "syncing"
      add :cursor_position, :map, default: %{}
      add :user_preferences, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :collaboration_id,
          references(:collaborations,
            column: :id,
            name: "collaboration_participants_collaboration_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "collaboration_participants_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:collaboration_participants, [:collaboration_id, :user_id],
             name: "collaboration_participants_unique_collaboration_user_index"
           )

    create table(:amfs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :jsonld_data, :map, null: false
      add :amf_hash, :text, null: false
      add :temporal, :map
      add :frequency_matrix, :map
      add :consciousness, :map
      add :patterns, :map
      add :dynamics, :map
      add :attention, :map
      add :semantic, :map
      add :format_version, :text, default: "2.0"
      add :base_frequency, :float
      add :consciousness_state, :text
      add :cognitive_load, :float
      add :duration_seconds, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "amfs_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :composition_id,
          references(:compositions,
            column: :id,
            name: "amfs_composition_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :pattern_id,
          references(:patterns,
            column: :id,
            name: "amfs_pattern_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:amfs, [:amf_hash], name: "amfs_unique_hash_index")

    create unique_index(:amfs, [:user_id, :name], name: "amfs_unique_name_per_user_index")
  end

  def down do
    drop_if_exists unique_index(:amfs, [:user_id, :name], name: "amfs_unique_name_per_user_index")

    drop_if_exists unique_index(:amfs, [:amf_hash], name: "amfs_unique_hash_index")

    drop constraint(:amfs, "amfs_user_id_fkey")

    drop constraint(:amfs, "amfs_composition_id_fkey")

    drop constraint(:amfs, "amfs_pattern_id_fkey")

    drop table(:amfs)

    drop_if_exists unique_index(:collaboration_participants, [:collaboration_id, :user_id],
                     name: "collaboration_participants_unique_collaboration_user_index"
                   )

    drop constraint(
           :collaboration_participants,
           "collaboration_participants_collaboration_id_fkey"
         )

    drop constraint(:collaboration_participants, "collaboration_participants_user_id_fkey")

    drop table(:collaboration_participants)

    drop constraint(:collaborations, "collaborations_composition_id_fkey")

    drop constraint(:collaborations, "collaborations_owner_id_fkey")

    drop table(:collaborations)

    drop_if_exists unique_index(:composition_patterns, [:composition_id, :pattern_id],
                     name: "composition_patterns_unique_composition_pattern_index"
                   )

    drop constraint(:composition_patterns, "composition_patterns_composition_id_fkey")

    drop constraint(:composition_patterns, "composition_patterns_pattern_id_fkey")

    drop table(:composition_patterns)

    drop_if_exists unique_index(:compositions, [:user_id, :title],
                     name: "compositions_unique_title_per_user_index"
                   )

    drop constraint(:compositions, "compositions_user_id_fkey")

    alter table(:compositions) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :tags
      remove :is_public
      remove :consciousness_params
      remove :amf_data
      remove :jsonld_graph
      remove :scoredown_content
      remove :title
    end

    drop_if_exists unique_index(:patterns, [:user_id, :name],
                     name: "patterns_unique_name_per_user_index"
                   )

    drop constraint(:patterns, "patterns_composition_id_fkey")

    alter table(:patterns) do
      modify :composition_id, :uuid
    end

    drop table(:compositions)

    drop constraint(:patterns, "patterns_user_id_fkey")

    drop table(:patterns)
  end
end
